### ISSUE TITLE
'character gear' command

### ISSUE THREAD

**Issue by knight0323** [digital-lagniappe/gw2tome-cli#2]
'character gear [character name]' 

This command will show the current equipment of the given character. It will list each piece of gear and include any sigils, runes, infusions, etc.

**Comment by Conan9287** [comment]
I'm intrigued on how this might work, because if so this will be extremely helpful for gearing up.

**Comment by knight0323** [comment]
Updated original description. @Conan9287, does the updated description help?

**Comment by Conan9287** [comment]
Yeah, it does.
